name: Build and Push Docker Image to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Image Tag
        run: echo "IMAGE_TAG=shortly:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_TAG .

      - name: Save Docker image to a tar file
        run: |
          docker save $IMAGE_TAG -o my-image-name.tar

      - name: Transfer Docker image to DigitalOcean droplet
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.DROPLET_USERNAME }}
          SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
        run: |
          scp -i "${SSH_KEY}" my-image-name.tar "${USERNAME}@${HOST}:/home/${USERNAME}/"

      - name: SSH into Droplet and Load Docker Image
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.DROPLET_USERNAME }}
          SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
        run: |
          ssh -i "${SSH_KEY}" "${USERNAME}@${HOST}" << 'EOF'
          sudo docker load -i /home/${USERNAME}/my-image-name.tar
          sudo docker run -d -p 8080:8080 my-image-name:latest
          EOF
